name: CI/CD
on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race ./...

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: |
          echo ${{ secrets.PASSWORD }} | docker login ghcr.io -u mrbelka12000 --password-stdin

      - name: Docker build
        run: |
          docker build -f build/Dockerfile -t ghcr.io/mrbelka12000/team_distributor .

      - name: Docker push
        run: |
          docker push ghcr.io/mrbelka12000/team_distributor

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_IP }} "docker service update --image ghcr.io/mrbelka12000/team_distributor mrbelka12000_team_distributor"

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'workflow_dispatch'
    environment: development

    env:
      OWNER: mrbelka12000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: |
          echo ${{ secrets.PASSWORD }} | docker login ghcr.io -u mrbelka12000 --password-stdin

      - name: Docker build
        run: |
          docker build -f build/Dockerfile -t ghcr.io/mrbelka12000/team_distributor .

      - name: Docker push
        run: |
          docker push ghcr.io/mrbelka12000/team_distributor

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_IP }} "docker service update --image ghcr.io/mrbelka12000/team_distributor mrbelka12000_team_distributor"
